# Generated by Django 3.0 on 2021-03-08 15:14

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('secretaria', models.CharField(blank=True, choices=[('SECRETARIAS', (('Assis. Social', 'Assis. Social'), ('Administração', 'Administração'), ('Cultura', 'Cultura'), ('Desenvolvimento', 'Desenvolvimento'), ('Esporte & Lazer', 'Esporte & Lazer'), ('Educação', 'Educação'), ('Fazenda', 'Fazenda'), ('Gabinete', 'Gabinete'), ('Habitação', 'Habitação'), ('Mulher', 'Mulher'), ('Meio ambiente', 'Meio ambiente'), ('Mineração, energia, ciência e tecnologia', 'Mineração, energia, ciência e tecnologia'), ('Produção Rural', 'Produção Rural'), ('Saúde', 'Saúde'), ('Secretaria de Obras', 'Secretaria de Obras'), ('Segurança e Defesa do Cidadão', 'Segurança e Defesa do Cidadão'), ('Turismo', 'Turismo'), ('Urbanismo', 'Urbanismo'), ('Sec. Especial de Governo', 'Sec. Especial de Governo'), ('Sec. Juventude', 'Sec. Juventude'))), ('COODENADORIAS', (('Recursos Humanos', 'Recursos Humanos'), ('Coord. de Terras', 'Coord. de Terras'), ('Tec. Informação e Tecnologia', 'Tec. Informação e Tecnologia'), ('Defesa Civil', 'Defesa Civil'), ('Polo Moveleiro', 'Polo Moveleiro'), ('Licitações e Contratos', 'Licitações e Contratos'))), ('OUTRAS', (('Assessoria de comunicação', 'Assessoria de comunicação'), ('Trânsito e Transporte', 'Trânsito e Transporte'), ('Relações com a Comunidade', 'Relações com a Comunidade'), ('Procuradoria Geral', 'Procuradoria Geral'), ('PROCON', 'PROCON'), ('Departamento de arrecadação', 'Departamento de arrecadação'), ('Controladoria Geral', 'Controladoria Geral')))], max_length=50, null=True, verbose_name='SECRETARIA')),
                ('departamento', models.CharField(blank=True, max_length=60, null=True, verbose_name='DEPARTAMENTO')),
                ('endereco', models.CharField(blank=True, max_length=60, null=True, verbose_name='ENDEREÇO')),
                ('responsavel', models.CharField(blank=True, max_length=60, null=True, verbose_name='RESPONSÁVEL')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.CreateModel(
            name='SoftwareOutro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_gratuito', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('7zip', '7zip'), ('Bizagi Modeler Free ', 'Bizagi Modeler Free'), ('Chrome', 'Chrome'), ('Adobe Reader DC ', 'Adobe Reader DC'), ('CutePDF Write Free', 'CutePDF Write Free'), ('doPDF', 'doPDF'), ('Firefox', 'Firefox'), ('Foxit Reader 7', 'Foxit Reader 7'), ('Google Earth', 'Google Earth'), ('Internet Explorer', 'Internet Explorer'), ('Java Run Time', 'Java Run Time'), ('K-Lite Codec Pack', 'K-Lite Codec Pack'), ('LibreOffice', 'LibreOffice'), ('Microsoft Power BI Desktop', 'Microsoft Power BI Desktop'), ('Modulo de segurança Bancário', 'Modulo de segurança Bancário'), ('QGIS', 'QGIS'), ('VLC–Player', 'VLC–Player'), ('Winrar', 'Winrar')], max_length=200, null=True, verbose_name='SOFTWARE GRATUITOS')),
                ('software_licenciado', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Adobe Acrobat DC', 'Adobe Acrobat DC'), ('Adobe Creative Cloud', 'Adobe Creative Cloud'), ('ArcGIS', 'ArcGIS'), ('AutoCAD', 'AutoCAD'), ('CorelDRAW', 'CorelDRAW'), ('Kaspersky Endpoint Security', 'Kaspersky Endpoint Security'), ('Microsoft Windows Office 2007 Professional', 'Microsoft Windows Office 2007 Professional'), ('Microsoft Windows Office 2010 Professional', 'Microsoft Windows Office 2010 Professional'), ('Microsoft Windows Office 2013 Professional', 'Microsoft Windows Office 2013 Professional'), ('Microsoft Windows Office 2016 Professional', 'Microsoft Windows Office 2016 Professional')], max_length=200, null=True, verbose_name='SOFTWARES LICENCIADOS')),
                ('licenca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº DA LICENÇA')),
                ('software_adminstrativo', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AdmCGM', 'AdmCGM'), ('AdmConvenio', 'AdmConvenio'), ('AdmPFiscal', 'AdmPFiscal'), ('AdmSEHAB', 'AdmSEHAB'), ('AdmSEMSA', 'AdmSEMSA'), ('AdmSEPLAN', 'AdmSEPLAN'), ('CPL Processos', 'CPL Processos'), ('CRCPL', 'CRCPL'), ('CplCGM ', 'CplCGM '), ('Desenvolve Parauapebas', 'Desenvolve Parauapebas'), ('NewBOAT', 'NewBOAT'), ('PGM Processos', 'PGM Processos'), ('PLAT - Registro de Atividades', 'PLAT - Registro de Atividades'), ('PatioController', 'PatioController'), ('Planeja Municipio', 'Planeja Municipio'), ('Processo Administrativo', 'Processo Administrativo'), ('Projeto Base', 'Projeto Base'), ('Prorural', 'Prorural'), ('SIM-Serviço de Inspeção Municipal', 'SIM-Serviço de Inspeção Municipal'), ('SISGEM-Escola de Música', 'SISGEM-Escola de Música'), ('SISPPAR-Sistema de Parcerias', 'SISPPAR-Sistema de Parcerias'), ('SisBOAT ', 'SisBOAT '), ('SisMulher ', 'SisMulher'), ('SisProtocolo', 'SisProtocolo'), ('Social', 'Social'), ('Transparência RH', 'Transparência RH'), ('WebVISA ', 'WebVISA')], max_length=200, null=True, verbose_name='SOFTWARES ADMINISTRATIVOS')),
                ('cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informatica.Secretaria')),
            ],
            options={
                'verbose_name': 'Outro Software',
                'verbose_name_plural': 'Outros Softwares',
            },
        ),
        migrations.CreateModel(
            name='SoftwareOs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_operacional', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SISTEMA OPERACIONAL TIPO WINDOWS', (('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows 10', 'Windows 10'), ('Windows XP', 'Windows XP'), ('Windows Vista', 'Windows Vista'))), ('SISTEMA OPERACIONAL TIPO UNIX', (('Debin', 'Debian'), ('Mint', 'Mint'), ('Fedora', 'Fedora'), ('Ubuntu', 'Ubuntu'))), ('OUTRO', (('DUAL BOOT', 'DUAL BOOT'),))], max_length=50, null=True, verbose_name='SISTEMA OPERACIONAL')),
                ('cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informatica.Secretaria')),
            ],
            options={
                'verbose_name': 'Sistema Operacional',
                'verbose_name_plural': 'Sistemas Operacionais',
            },
        ),
        migrations.CreateModel(
            name='Nobreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aquisicao_equipamento', models.CharField(blank=True, choices=[('Patrimônio', 'Patrimônio'), ('Contrato', 'Contrato'), ('Sem Patrimônio', 'Sem Patrimônio')], max_length=50, null=True, verbose_name='TIPO DE AQUISIÇÃO')),
                ('patrimonio_nobreak', models.CharField(blank=True, max_length=50, null=True, verbose_name='PATRIMÔNIO NOBREAK')),
                ('nobreak', models.CharField(blank=True, choices=[('400VA', '400VA'), ('500VA', '500VA'), ('600VA', '600VA'), ('700VA', '700VA'), ('800VA', '800VA'), ('1000VA', '1000VA'), ('1200VA', '1200VA'), ('1300VA', '1300VA'), ('1400VA', '1400VA'), ('1600VA', '1600VA'), ('1800VA', '1800VA'), ('2400VA', '2400VA')], max_length=50, null=True, verbose_name='TENSÃO')),
                ('cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informatica.Secretaria')),
            ],
            options={
                'verbose_name': 'Nobreak',
                'verbose_name_plural': 'Nobreaks',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aquisicao_equipamento', models.CharField(blank=True, choices=[('Patrimônio', 'Patrimônio'), ('Contrato', 'Contrato'), ('Sem Patrimônio', 'Sem Patrimônio')], max_length=50, null=True, verbose_name='TIPO DE AQUISIÇÃO')),
                ('patrimonio_monitor', models.CharField(blank=True, max_length=50, null=True, verbose_name='PATRIMÔNIO MONITOR')),
                ('tamanho', models.CharField(blank=True, choices=[('14 Polegadas', '14 Polegadas'), ('15.6 Polegadas', '15.6 Polegadas'), ('17 Polegadas', '17 Polegadas'), ('18.5 Polegadas', '18.5 Polegadas'), ('19 Polegadas', '19 Polegadas'), ('20 Polegadas', '20 Polegadas'), ('21.5 Polegadas', '21.5 Polegadas'), ('24 Polegadas', '24 Polegadas'), ('25 Polegadass', '25 Polegadas'), ('27 Polegadas', '27 Polegadas'), ('28 Polegadas', '28 Polegadas'), ('31,5 Polegadas', '31,5 Polegadas')], max_length=50, null=True, verbose_name='TAMANHO')),
                ('cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informatica.Secretaria')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aquisicao_equipamento', models.CharField(blank=True, choices=[('Patrimônio', 'Patrimônio'), ('Contrato', 'Contrato'), ('Sem Patrimônio', 'Sem Patrimônio')], max_length=50, null=True, verbose_name='TIPO DE AQUISIÇÃO')),
                ('patrimonio_impressora', models.CharField(blank=True, max_length=50, null=True, verbose_name='PATRIMÔNIO IMPRESSORA')),
                ('impressora_multi_fax', models.BooleanField(blank=True, max_length=50, verbose_name='POSSUI FAX?')),
                ('impressora_multi_scanner', models.BooleanField(blank=True, max_length=50, verbose_name='POSSUI SCANNER?')),
                ('impressora_marca', models.CharField(blank=True, choices=[('Brother', 'Brother'), ('Ricoh', 'Ricoh'), ('Canon', 'Canon'), ('Samsung', 'Samsung'), ('Elgin', 'Elgin'), ('Epson', 'Epson'), ('Hp', 'Hp'), ('Kyocera', 'Kyocera'), ('Lexmark', 'Lexmark'), ('Xerox', 'Xerox'), ('MITSUSHIBA', 'MITSUSHIBA'), ('Maxprint', 'Maxprint'), ('PCYes', 'PCYes')], max_length=50, null=True, verbose_name='MARCA')),
                ('impressora_tipo', models.CharField(blank=True, choices=[('Jato de Tinta', 'Jato de Tinta'), ('Laser', 'Laser'), ('Pagewide', 'Pagewide'), ('Plotter', 'Plotter'), ('Térmica', 'Térmica'), ('Matricial', 'Matricial'), ('Portátil', 'Portátil'), ('Fotográfica', 'Fotográfica')], max_length=50, null=True, verbose_name='TIPO')),
                ('impressora_impressao', models.CharField(blank=True, choices=[('Monocromático', 'Monocromático'), ('Colorido', 'Colorido')], max_length=50, null=True, verbose_name='IMPRESSÃO')),
                ('cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informatica.Secretaria')),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aquisicao_equipamento', models.CharField(blank=True, choices=[('Patrimônio', 'Patrimônio'), ('Contrato', 'Contrato'), ('Sem Patrimônio', 'Sem Patrimônio')], max_length=50, null=True, verbose_name='TIPO DE AQUISIÇÃO')),
                ('patrimonio_pc', models.CharField(blank=True, max_length=50, null=True, verbose_name='PATRIMÔNIO PC')),
                ('processador', models.CharField(blank=True, choices=[('AMD A', 'AMD A'), ('AMD Athlon/Sempron', 'AMD Athlon/Sempron'), ('AMD FX', 'AMD FX'), ('AMD Phenom', 'AMD Phenom'), ('AMD Ryzen 3', 'AMD Ryzen 3'), ('AMD Ryzen 5', 'AMD Ryzen 5'), ('AMD Ryzen 7', 'AMD Ryzen 7'), ('INTEL Atom', 'INTEL Atom'), ('INTEL Celeron', 'INTEL Celeron'), ('INTEL Pentium', 'INTEL Pentium'), ('INTEL Core i3', 'INTEL Core i3'), ('INTEL Core i5', 'INTEL Core i5'), ('INTEL Core i7', 'INTEL Core i7')], max_length=50, null=True, verbose_name='PROCESSADOR')),
                ('hdd_ssd', models.CharField(blank=True, choices=[('80 GB', '80 GB'), ('100 GB', '100 GB'), ('120 GB', '120 GB'), ('160 GB', '160 GB'), ('200 GB', '200 GB'), ('250 GB', '250 GB'), ('500 GB', '500 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('3 TB', '3 TB'), ('4 TB', '4 TB')], max_length=50, null=True, verbose_name='HDD/SSD')),
                ('memoria_ram', models.CharField(blank=True, choices=[('1 GB', '1 GB'), ('2 GB', '2 GB'), ('3 GB', '3 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('12 GB', '12 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB')], max_length=50, null=True, verbose_name='MEMORIA RAM')),
                ('placa_grafica', models.CharField(blank=True, choices=[('Classe A', 'Classe A'), ('Classe B', 'Classe B'), ('Classe C', 'Classe C'), ('Não', 'Não')], max_length=50, null=True, verbose_name='PLACA GRÁFICA')),
                ('cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informatica.Secretaria')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
    ]
