# Generated by Django 3.0 on 2021-03-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computador',
            options={'verbose_name': 'Computador', 'verbose_name_plural': 'Computadores'},
        ),
        migrations.AlterModelOptions(
            name='impressora',
            options={'verbose_name': 'Impressora', 'verbose_name_plural': 'Impressoras'},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'verbose_name': 'Monitor', 'verbose_name_plural': 'Monitores'},
        ),
        migrations.AlterModelOptions(
            name='nobreak',
            options={'verbose_name': 'Nobreak', 'verbose_name_plural': 'Nobreaks'},
        ),
        migrations.AlterModelOptions(
            name='softwareos',
            options={'verbose_name': 'Sistema Operacional', 'verbose_name_plural': 'Sistemas Operacionais'},
        ),
        migrations.AlterModelOptions(
            name='softwareoutro',
            options={'verbose_name': 'Outro Software', 'verbose_name_plural': 'Outros Softwares'},
        ),
        migrations.RenameField(
            model_name='secretaria',
            old_name='responsalvel',
            new_name='responsavel',
        ),
        migrations.AlterField(
            model_name='computador',
            name='memoria_ram',
            field=models.CharField(blank=True, choices=[('1 GB', '1 GB'), ('2 GB', '2 GB'), ('3 GB', '3 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('12 GB', '12 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB')], max_length=50, null=True, verbose_name='MEMORIA RAM'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='placa_grafica',
            field=models.CharField(blank=True, choices=[('Classe A', 'Classe A'), ('Classe B', 'Classe B'), ('Classe C', 'Classe C'), ('Não', 'Não')], max_length=50, null=True, verbose_name='PLACA GRÁFICA'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='aquisição_equipamento',
            field=models.CharField(blank=True, choices=[('Patrimônio', 'Patrimônio'), ('Contrato', 'Contrato'), ('Sem Patrimônio', 'Sem Patrimônio')], max_length=50, null=True, verbose_name='TIPO DE AQUISIÇÃO'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('14 Polegadas', '14 Polegadas'), ('15.6 Polegadas', '15.6 Polegadas'), ('17 Polegadas', '17 Polegadas'), ('18.5 Polegadas', '18.5 Polegadas'), ('19 Polegadas', '19 Polegadas'), ('20 Polegadas', '20 Polegadas'), ('21.5 Polegadas', '21.5 Polegadas'), ('24 Polegadas', '24 Polegadas'), ('25 Polegadass', '25 Polegadas'), ('27 Polegadas', '27 Polegadas'), ('28 Polegadas', '28 Polegadas'), ('31,5 Polegadas', '31,5 Polegadas')], max_length=50, null=True, verbose_name='TAMANHO'),
        ),
        migrations.AlterField(
            model_name='nobreak',
            name='nobreak',
            field=models.CharField(blank=True, choices=[('400VA', '400VA'), ('500VA', '500VA'), ('600VA', '600VA'), ('700VA', '700VA'), ('800VA', '800VA'), ('1000VA', '1000VA'), ('1200VA', '1200VA'), ('1300VA', '1300VA'), ('1400VA', '1400VA'), ('1600VA', '1600VA'), ('1800VA', '1800VA'), ('2400VA', '2400VA')], max_length=50, null=True, verbose_name='TENSÃO'),
        ),
    ]
