# Generated by Django 3.0 on 2021-03-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0002_auto_20210308_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='aquisição_equipamento',
            new_name='aquisicao_equipamento',
        ),
    ]
