# Generated by Django 3.0 on 2021-03-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0003_auto_20210308_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='aquisição_equipamento',
            new_name='aquisicao_equipamento',
        ),
        migrations.RenameField(
            model_name='impressora',
            old_name='aquisição_equipamento',
            new_name='aquisicao_equipamento',
        ),
        migrations.RenameField(
            model_name='nobreak',
            old_name='aquisição_equipamento',
            new_name='aquisicao_equipamento',
        ),
    ]
