# Generated by Django 3.0 on 2021-03-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0004_auto_20210308_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressora',
            name='patrimonio_pc',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='patrimonio_pc',
        ),
        migrations.RemoveField(
            model_name='nobreak',
            name='patrimonio_pc',
        ),
        migrations.AddField(
            model_name='impressora',
            name='patrimonio_impressora',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PATRIMÔNIO IMPRESSORA'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='patrimonio_monitor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PATRIMÔNIO MONITOR'),
        ),
        migrations.AddField(
            model_name='nobreak',
            name='patrimonio_nobreak',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PATRIMÔNIO NOBREAK'),
        ),
    ]
