# Generated by Django 3.0 on 2021-03-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0005_auto_20210308_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareoutro',
            old_name='software_adminstrativos',
            new_name='software_adminstrativo',
        ),
        migrations.RenameField(
            model_name='softwareoutro',
            old_name='software_gratuitos',
            new_name='software_gratuito',
        ),
        migrations.RenameField(
            model_name='softwareoutro',
            old_name='software_licenciados',
            new_name='software_licenciado',
        ),
    ]
