# Generated by Django 3.0 on 2021-03-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0006_auto_20210308_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informatica.SoftwareOutro'),
        ),
    ]
