# Generated by Django 3.0 on 2021-03-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0007_computador_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='software',
        ),
        migrations.AddField(
            model_name='computador',
            name='software',
            field=models.ManyToManyField(null=True, to='informatica.SoftwareOutro'),
        ),
    ]
