# Generated by Django 3.0 on 2021-03-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0009_auto_20210308_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='software',
        ),
        migrations.AddField(
            model_name='computador',
            name='software',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informatica.SoftwareOutro'),
        ),
    ]
