# Generated by Django 3.0 on 2021-03-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0010_auto_20210308_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='software',
        ),
    ]
